name: build-test
on:
  push: ~

jobs:
  test-run:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - macos-12
          - macos-11
          - ubuntu-latest
          - ubuntu-22.04
          - ubuntu-20.04
          - windows-latest
          - windows-2022
          - windows-2019
        version:
          - latest
          - v1.13.2
          - 1.13.2
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup dasel
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Ensure dasel is installed
        run: |
          dasel --help
