name: build-test
on:
  push: ~

jobs:
  test-run:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
          - windows-2019
        version:
          - latest
          - v1.13.2
          - 1.13.2
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup dasel
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Ensure dasel is installed
        run: |
          dasel --help
